---
title: "Metodo de la convolucion"
author: "Cristian Alejandro Castrejon Lara"
date: "2026-04-23"
output: html_document
---
**EJEMPLO 1**
```{r}
set.seed(42)

lambda1 <- 3 #Parametro primera distribucion exponencial
lambda2 <- 3 #Parametro segunda distribucion exponencial
n_simulaciones <- 10000
U1 <- runif(n_simulaciones) #Para la primera distribucion
U2 <- runif(n_simulaciones) #Para la segunda distribucion

X1 <- qexp(p = U1, rate = lambda1)
X2 <- qexp(p = U2, rate = lambda2)

X_simulados <- X1+X2
head(X_simulados)

hist(X_simulados,
     probability = T,
     col = "blue",
     border = "white",
     breaks = 30,
     main = "Distribucion Suma de 2 Exponenciales")

lines(density(X_simulados), col = "red", lwd = 2)

f_teorica <- function(x){
  ifelse( x<0 , 0 , 9*x*exp(-3*x))
}

curve(f_teorica, col = "green", lwd = 2 , add = T)
```
**EJEMPLO 2**
```{r}
set.seed(42)

lambda <- 2 #Parametro primera distribucion exponencial
a <- 0
b <- 1
n_simulaciones <- 10000
U1 <- runif(n_simulaciones) #Para la primera distribucion
U2 <- runif(n_simulaciones) #Para la segunda distribucion

X1 <- qexp(p = U1, rate = lambda)
X2 <- qunif(p = U2, min = a, max = b)#se puede hacer con runif porque genera
#valores aleatorios del 0 al 1
X_simulados <- X1+X2
head(X_simulados)

hist(X_simulados,
     probability = T,
     col = "blue",
     border = "white",
     breaks = 30,
     main = "Distribucion Suma de Exponenciales Con Uniforme")

lines(density(X_simulados), col = "red", lwd = 2)

f_teorica <- function(x){
  ifelse( x<0 , 0 , 
          ifelse(x < 1, 1 - exp(-2*x), exp(-2*x)*(exp(2)-1)))
}

curve(f_teorica, col = "green", lwd = 2 , add = T)
```
**EJEMPLO 3**
```{r}
set.seed(42)


n_simulaciones <- 10000
U1 <- runif(n_simulaciones) #Para la primera distribucion
U2 <- runif(n_simulaciones) #Para la segunda distribucion
U3 <- runif(n_simulaciones) #Para la tercera distribucion

X <- qunif(p = U1)
Y <- U2
W <- U3
Z <- X+Y+W


hist(Z,
     probability = T,
     col = "blue",
     border = "white",
     breaks = 30,
     main = "Distribucion Suma de 3 Uniformes (0,1)")

lines(density(Z), col = "red", lwd = 2)

f_teorica <- function(z){
  ifelse( z<0 , 0 , 
          ifelse(z < 1, (z^2)/2 ,
                 ifelse(z<2, (-z^2)+3*z-(3/2), ((z-3)^2)/2)))
}

curve(f_teorica, col = "green2", lwd = 3 , add = T)
```
**EJEMPLO 4**
```{r}
set.seed(42)


n_simulaciones <- 10000
U1 <- runif(n_simulaciones) #Para la primera distribucion
U2 <- runif(n_simulaciones) #Para la segunda distribucion
p <- 0.5 #Parametro de la bernoulli
X <- qbinom(p = U1, size = 1, prob = p)
Y <- ifelse( U2 <= 1/3, 1, 
             ifelse(U2 <= 2/3, 2, 3))
Z <- X+Y

frecuencias_empiricas <- table(Z)/n_simulaciones
frecuencias_teoricas <- c(1/6,1/3,1/3,1/6)
contraste <- rbind(frecuencias_empiricas, frecuencias_teoricas)
barplot(contraste, beside = T, col = c("red","blue" ))

```

